name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}