name: Test
on:
  push:
    branches:
      - feature/**
      - release/**
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - uses: ./
        id: plain1 with desc
        with:
          template: plain1
          description: Description only
      - uses: ./
        id: plain1 with title & desc
        with:
          template: plain1
          description: Description
          title: Title with
      - uses: ./
        with:
          template: plain2
      - uses: ./
        with:
          template: plain2
          title: ${{ job.status }}
      - uses: ./
        with:
          template: plain1
          description: Override the default channel
          channel: '#projects'
      - uses: ./
        with:
          template: plain1
          description: Override username
          username: Foo
      - uses: ./
        with:
          template: plain1
          description: Override icon_emoji
          icon_emoji: ":fire:"
      - uses: ./
        with:
          template: plain1
          description: Override icon_url
          icon_url: https://octodex.github.com/images/original.png
      - uses: ./
        with:
          template: push1
          status: ${{ job.status }}
      - uses: ./
        with:
          template: steps1
          steps: ${{ toJSON(steps) }}